### PR TITLE
allows optional specifying of a limit for query

### PR DESCRIPTION
**Pull request by lonelydimple**
WIP

This allows the credit_puller to call:
```ruby
initialize_grid(CreditReport, limit: 10)
````
- [ ] figure out how to test this within wice_grid
- [ ] submit upstream PR to wice_grid to include this feature

### CODE REVIEW

**Comment by Capncavedan** [comment]
is your thought to specify, say, a limit of 0 on initial  index page load?

**Comment by lonelydimple** [comment]
That seems like a possibility. Also, didn't think it would be too much of
an exposure to display the 10 most recent credit reports either. Users will
be able to get to credit reports if they want, this just makes it a little
harder.

Sometimes, it all seems a little pointless. :)

**Comment by lonelydimple** [comment]
Actually, that wouldn't work. 

During testing, I tried to set a default of zero and wice_grid does not like that, throws a "divide by zero" error for some reason. If we wanted to do that we'd need to investigate a little further what wice_grid is doing with that passed in option.

**Comment by lonelydimple** [comment]
Setting aside for now ... revisit with commercial/compliance when there are more credit reports to design a good way to limit browsability while still allowing employees to find what they're looking for.

**Pull request closed without merging**
